from django.urls import path

from .views import (
    HelloView,
    RegisterView,
    LoginView,
    ChangePasswordView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    MeView,
    WalletSummaryView,
    WalletTransactionListView,
    WalletDepositView,
    WalletSpendView,
    ProfileStatsView,
    ReferralTreeView,
    ReferralRewardsView,
    WithdrawalRequestListCreateView,
    AdminMemberListCreateView,
    AdminMemberDetailView,
    AdminResetMemberPasswordView,
    AdminReferralEventListView,
    AdminStatsOverviewView,
    TestSimulateDepositsView,
    SimulateDemoDepositsView,
    BusinessModelSimulationView,
)

urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path(
        "auth/password-reset/request/",
        PasswordResetRequestView.as_view(),
        name="password-reset-request",
    ),
    path(
        "auth/password-reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path("auth/me/", MeView.as_view(), name="me"),
    path(
        "wallet/summary/",
        WalletSummaryView.as_view(),
        name="wallet-summary",
    ),
    path(
        "wallet/transactions/",
        WalletTransactionListView.as_view(),
        name="wallet-transactions",
    ),
    path(
        "wallet/deposit/",
        WalletDepositView.as_view(),
        name="wallet-deposit",
    ),
    path(
        "wallet/spend/",
        WalletSpendView.as_view(),
        name="wallet-spend",
    ),
    path("profile/stats/", ProfileStatsView.as_view(), name="profile-stats"),
    path(
        "referrals/tree/",
        ReferralTreeView.as_view(),
        name="referral-tree",
    ),
    path(
        "referrals/rewards/",
        ReferralRewardsView.as_view(),
        name="referral-rewards",
    ),
    path(
        "withdrawal-requests/",
        WithdrawalRequestListCreateView.as_view(),
        name="withdrawal-requests",
    ),
    path(
        "admin/members/",
        AdminMemberListCreateView.as_view(),
        name="admin-members-list-create",
    ),
    path(
        "admin/members/<int:pk>/",
        AdminMemberDetailView.as_view(),
        name="admin-members-detail",
    ),
    path(
        "admin/members/<int:pk>/reset-password/",
        AdminResetMemberPasswordView.as_view(),
        name="admin-members-reset-password",
    ),
    path(
        "admin/referrals/",
        AdminReferralEventListView.as_view(),
        name="admin-referrals-list",
    ),
    path(
        "admin/stats/overview/",
        AdminStatsOverviewView.as_view(),
        name="admin-stats-overview",
    ),
    path(
        "test/simulate-deposits/",
        TestSimulateDepositsView.as_view(),
        name="test-simulate-deposits",
    ),
    path(
        "test/simulate_demo_deposits/",
        SimulateDemoDepositsView.as_view(),
        name="simulate-demo-deposits",
    ),
    path(
        "test/simulate-business-model/",
        BusinessModelSimulationView.as_view(),
        name="simulate-business-model",
    ),
]
